[package]
name = "waymaker-partial"
version = "0.0.30"
edition = "2024"
license = "MIT"
repository = "https://github.com/Squirreljetpack/matchmaker"
description = "Support for partial updates and configuration in waymaker"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"

[dev-dependencies]
indexmap = { version = "2.14.0", features = ["serde"] }
waymaker-partial-macros = { path = "../waymaker-partial-macros", features = ["partial"] }
toml = "0.9.8"

[[test]]
name = "derive_macro_test"
path = "tests/macro_test.rs"

[[test]]
name = "macro_optional_test"
path = "tests/option_wrap.rs"

[[test]]
name = "penetration_test"
path = "tests/penetration_test.rs"

[[test]]
name = "set_recurse_test"
path = "tests/set_recurse_test.rs"

[lints]
workspace = true
