# Preset to run cargo examples and binaries

[start.command]
command = '''
# Examples
if [ -f Cargo.toml ]; then
  input="$(yq -r '.example[] | select(length > 0) | [.name, (.path // "examples/" + .name + ".rs"), (.required-features // [] | join(","))] | @tsv' Cargo.toml 2>/dev/null)"
fi

# Crawl if unspecified in Cargo.toml
if [ -z "$input" ]; then
  input="$(
    for f in examples/*.rs; do
      [ -f "$f" ] || continue
      name="$(basename "$f" .rs)"
      printf "%s\t%s\t\n" "$name" "$f"
    done
    for d in examples/*/src/main.rs; do
      [ -f "$d" ] || continue
      name=$(basename "$(dirname "$(dirname "$d")")")
      printf "%s\t%s\t\n" "$name" "$d"
    done
  )"
fi

# Binaries
if [ -f Cargo.toml ]; then
  bin_input="$(yq -r '.bin[] | select(length > 0) | [.name, (.path // "src/bin/" + .name + ".rs"), (.required-features // [] | join(","))] | @tsv' Cargo.toml 2>/dev/null)"
fi

if [ -z "$bin_input" ]; then
  bin_input="$(
    for f in src/bin/*.rs; do
      [ -f "$f" ] || continue
      name="$(basename "$f" .rs)"
      printf "%s\t%s\t\n" "$name" "$f"
    done
    for d in src/bin/*/main.rs; do
      [ -f "$d" ] || continue
      name="$(basename "$(dirname "$d")")"
      printf "%s\t%s\t\n" "$name" "$d"
    done
    [ -f src/main.rs ] && printf "main\tsrc/main.rs\t\n"
  )"
fi

# Targets
target_input="$(
  for f in target/{debug,release}/*; do
    [ -x "$f" ] && [ -f "$f" ] || continue
    [[ "$f" == */deps/* ]] && continue
    name="$(basename "$f") ($(basename $(dirname "$f")))"
    printf "%s\t%s\t\n" "$name" "$f"
  done 2>/dev/null
)"

[ -n "$input" ] && echo "$input" | sed 's/^/ex\t/'
[ -n "$bin_input" ] && echo "$bin_input" | sed 's/^/bin\t/'
[ -n "$target_input" ] && echo "$target_input" | sed 's/^/target\t/'
'''

[columns]
split = '\t'
max = 4
default = "name"
names = ["kind", "name", "path", "flags"]

[preview]
[[preview.layout]]
command = '''
f={path}

if [ {kind} = "target" ]; then
  if command -v fs >/dev/null 2>&1; then
    fs :tool lessfilter info "$f"
  else
    ls -l "$f"
  fi
else
  [ -e "$f" ] || f="${f%???}/main.rs"
  if command -v bat >/dev/null 2>&1; then
    bat --wrap=never --color=always -pp "$f"
  else
    cat "$f"
  fi
fi
'''

[binds]
"@accept" = '''Transform(
  features={4}
  [[ -n "$features" ]] && features="-F $features"

  case {1} in
    target)
      echo "Become({path} {$0})"
      ;;
    ex)
      echo "Become(cargo run --example {name} $features {$0})"
      ;;
    bin|*)
      echo "Become(cargo run --bin {name} $features {$0})"
      ;;
  esac
)
'''
"@Accept" = "Accept"
"ctrl-1" = "@summary"

"@summary" = '''Execute(
  $PAGER "$(dirname -- "$(dirname -- {path})")/Cargo.toml"
)
'''
