[matcher]
ansi = true

[start.command]
command = 'man -k "$@"'

[envs]
MANcmd = { value = 'command -v batman >/dev/null && echo batman || echo man', exec = true }

[columns]
split = "\\s+-"
max = 2

[preview]
show = true

[[preview.layout]]
command = '''entry={1}; $MANcmd ${entry%%\(*}'''
