# Browse and ssh into your tailnet

[start.command]
command = "tailscale status | awk 'NF{print; next} {exit}'"

[columns]
# tailscale status output:
# 100.100.100.100  hostname             user@        os      status
split = '\s+'
names = ["ip", "hostname", "user", "os", "status"]

[envs]
TAILSCALE_BE_CLI = "1"

# --- Preview ---
[preview]
show = true

[[preview.layout]]
command = "tailscale ping --verbose {hostname}"
border = { title = "Ping" }

[[preview.layout]]

[[preview.layout]]
command = "tailscale status --json"
border = { title = "Tailnet Status" }

# --- UI ---
[header]
content = ["ip", "hostname", "user", "os", "status"]

[query]
prompt = "tailscale> "

[binds]
"ctrl-n" = "@netcheck"

"@accept" = "Become(echo {ip})"
"@Accept" = "Accept"
"@open" = "Become(tailscale ssh {hostname})"
"@open_2" = "ExecuteSilent(fs :o https://login.tailscale.com/admin/machines)"
"@next" = "BecomeSilent(mm -o ssh/hosts)"
"@prev" = "BecomeSilent(mm -o ssh/known)"

# --- Scripts ---
"@netcheck" = "Preview(tailscale netcheck)"
