[package]
name = "matchmaker-cli"
version = "0.1.6"
authors = ["Squirreljetpack"]
categories = ["command-line-utilities"]
edition = "2024"
exclude = ["assets/completions", "assets/presets"]
homepage = "https://github.com/Squirreljetpack/matchmaker"
keywords = ["fuzzy", "finder", "tui", "nucleo", "fzf"]
license = "MIT"
repository = "https://github.com/Squirreljetpack/matchmaker"
description = "Command-line interface for the matchmaker fuzzy finder"

[package.metadata.dist]
dist = true
name = "matchmaker"
display-name = "matchmaker"
features = ["experimental"]
formula = "matchmaker"
npm-package = "matchmaker"

[package.metadata.wix]
upgrade-guid = "97859E79-FF52-4C64-9626-FE7E0FDA78E4"
path-guid = "1BEFEDD3-26B2-471B-8196-2BCF87E28476"
license = false
eula = false

[dependencies]
cli_boilerplate_automation = { workspace = true, features = ["serde", "bring"] }
indexmap = { version = "2.14.0", features = ["serde"] }
matchmaker-lib = { workspace = true, features = ["partial"] }
matchmaker-partial = { workspace = true }
matchmaker-partial-macros = { workspace = true }

ansi-to-tui = "8.0.1"
anyhow = "1.0"
arc-swap = "1.9.2"
atoi = "3.1"
atty = "0.2.14"
base64 = "0.23.1"
clap = { version = "4.6.5", features = ["derive"] }
crokey = "1.5.0"
dirs = "6.0.0"
easy-ext = "1.0.3"
env_logger = "0.11.11"
log = "0.4"
mimalloc = "0.1"
minus = { package = "matchmaker-minus", version = "5.*", features = ["dynamic_output", "search", "clipboard"], optional = true }
mlua = { version = "0.10", features = ["lua54", "vendored"], optional = true }
regex = "1"
serde = "1.0"
serde_json = "1.0"
termimad = "0.35"
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }
toml = "1.1"
which = "8.0"

[build-dependencies]
clap = { version = "4.6", features = ["derive"] }
clap_complete = "4.6"
strum = { version = "0.28", features = ["strum_macros"] }
thiserror = "2.0.19"

[[bin]]
name = "mm"
path = "src/main.rs"

[lints]
workspace = true

[features]
default = ["mlua", "pager"]
mlua = ["dep:mlua"]
pager = ["dep:minus"]
experimental = [
    "matchmaker-lib/experimental",
    # "log/max_level_debug"
]

[target.'cfg(unix)'.dependencies]
libc = "0.2"
