# Unicode Character Database

[start.command]
command = '''zstd -dc "$(dirname -- "$MM_OVERRIDE")"/unicode.zst'''

[envs]
ACTIVE_DICT = "unicode"

[query]
prompt = "unicode> "

[header]
content = ['char', 'name', 'cat']

[columns]
split = ";"
names = ["char", "name", "cat"]
default = "name"

# --- Preview ---

[[preview.layout]]
command = '''
char={char}
hex=$(printf "U+%X\n" "'$char")
printf "%${COLUMNS}s\n" | tr ' ' '-'
echo "  $char  "{name}
printf "%${COLUMNS}s\n" | tr ' ' '-'
echo "Code:     $hex"
echo "Category: "{cat}
'''

# --- UI ---
[results]
min_width = 5

[binds]
"@show" = '''RunPreview(
    echo "Category Descriptions:"
    printf "%${COLUMNS}s\n" | tr ' ' '-'
    echo "Lu: Letter, Uppercase"
    echo "Ll: Letter, Lowercase"
    echo "Lt: Letter, Titlecase"
    echo "Lm: Letter, Modifier"
    echo "Lo: Letter, Other"
    echo "Mn: Mark, Nonspacing"
    echo "Mc: Mark, Spacing Combining"
    echo "Me: Mark, Enclosing"
    echo "Nd: Number, Decimal Digit"
    echo "Nl: Number, Letter"
    echo "No: Number, Other"
    echo "Pc: Punctuation, Connector"
    echo "Pd: Punctuation, Dash"
    echo "Ps: Punctuation, Open"
    echo "Pe: Punctuation, Close"
    echo "Pi: Punctuation, Initial quote"
    echo "Pf: Punctuation, Final quote"
    echo "Po: Punctuation, Other"
    echo "Sm: Symbol, Math"
    echo "Sc: Symbol, Currency"
    echo "Sk: Symbol, Modifier"
    echo "So: Symbol, Other"
    echo "Zs: Separator, Space"
    echo "Zl: Separator, Line"
    echo "Zp: Separator, Paragraph"
    echo "Cc: Other, Control"
    echo "Cf: Other, Format"
    echo "Cs: Other, Surrogate"
    echo "Co: Other, Private Use"
    echo "Cn: Other, Unassigned"
)'''

"@copy" = "CopyAsync(echo {char})"
"@copy_all" = '''CopyAsync(
    char={char}
    printf "\\\\u{%X}" "'$char"
)'''
"@accept" = ["Print({=char})", "Quit(0)"]
"tty^^@accept" = ["Copy(echo {char})", "Quit(0)"]
