# Docker/Podman image viewer
source = "base.toml"

[matcher]
trim = true

[start]
[start.command]
command = '$DOCKERcmd image ls --format "{{.Repository}}	{{.Tag}}	{{.ID}}	{{.CreatedAt}}	{{.Size}}"'
input_separator = "\n"

[header]
header_lines = 1
# content = ["REPOSITORY", "TAG", "IMAGE ID", "CREATED", "SIZE"]

[columns]
split = "\\t\\s*"
names = ["repo", "tag", "id", "created", "size"]

[[preview.layout]]
# History
command = '''$DOCKERcmd ps -a --filter ancestor={id} --format \
"
{{.ID}}
{{.Status}}
{{.Created}}

names: {{.Names}}
------------
"

'''
border = { title = "Containers" }

[[preview.layout]]
# History
command = "$DOCKERcmd image history {id}"
border = { title = "Image History" }

[[preview.layout]]
# Inspect
command = "$DOCKERcmd image inspect {id} | PG_LANG=json $PAGER"
border = { title = "Image Inspect" }

[binds]
# Navigation
"ctrl-o" = "SwitchPreview(1)"

# Management Actions
"ctrl-r" = "@pull"
"alt-r" = "@push"
"ctrl-d" = "@rmi"
"alt-d" = "@rmi_id"
"alt-s" = "@save_tar"
"ctrl-n" = "@copy_tag"
"alt-n" = "@rename_tag"
"ctrl-t" = "@new_tag"
"alt-t" = "@retag"

# --- Actions ---
"@config_exec" = "Execute($DOCKERcmd image inspect {id} | PG_LANG=json $PAGER)"
"@stats" = "Preview($DOCKERcmd image history {id})"

"@pull" = 'ExecuteOrConfirm($DOCKERcmd image pull {repo}:{tag}) Status(Pulling...)'
"@push" = 'ExecuteOrConfirm($DOCKERcmd image push {repo}:{tag}) Status(Pushing...)'

"@rmi" = ["ExecuteOrConfirm($DOCKERcmd image rmi {repo}:{tag}) Status(Removing...)", "Reload"]
"@rmi_id" = ["ExecuteOrConfirm($DOCKERcmd image rmi {id}) Status(Removing by ID...)", "Reload"]

"@save_tar" = '''ExecuteOrConfirm(
        printf "Save as (filename): "
        read -r filename
        if [[ -n "$filename" ]]; then
            $DOCKERcmd image save {id} -o "$filename"
        fi
    )'''

"@copy_tag" = '''ExecuteOrConfirm(
        printf "Copy {repo}:{tag} to (new name): "
        read -r newname
        if [[ -n "$newname" ]]; then
            $DOCKERcmd image tag {id} "$newname"
        fi
    )'''

"@rename_tag" = '''ExecuteOrConfirm(
        printf "Rename {repo}:{tag} to (new name): "
        read -r newname
        if [[ -n "$newname" ]]; then
            $DOCKERcmd image tag {id} "$newname" &&
            $DOCKERcmd image rmi {repo}:{tag}
        fi
    )'''

"@new_tag" = '''ExecuteOrConfirm(
        printf "New tag for {repo} -> {repo}:"
        read -r newtag
        if [[ -n "$newtag" ]]; then
            $DOCKERcmd image tag {id} "{repo}:$newtag"
        fi
    )'''

"@retag" = '''ExecuteOrConfirm(
        printf "Retag {repo}:{tag} -> {repo}:"
        read -r newtag
        if [[ -n "$newtag" ]]; then
            $DOCKERcmd image tag {id} "{repo}:$newtag" &&
            $DOCKERcmd image rmi {repo}:{tag}
        fi
    )'''

[query]
prompt = "images> "
prompt_style.fg = "Magenta"

[tui]
percentage = 100
