# Podman container mount tool
source = "base.toml"

[start]
[start.command]
    command         = '"$(dirname -- "$MM_OVERRIDE")"/containers.sh'
    input_separator = "\\0"
    trim            = true

[columns]
    split = "\\t"
    names = [ "name", "status", "id", "image", "state" ]

[envs]
    JQ = "jq"

[binds]
    "enter" = "@mount"

    # --- Actions ---
    "@mount" = '''Become(
        container_id={id}
        mounted_dir=$(podman unshare -- podman mount "$container_id") || { echo "Mount failed" && read; exit 1; }
        echo "Mounted at: $mounted_dir"
        echo "$mounted_dir" | tee >(${=CLIPcmd})
        cd "$mounted_dir"
        echo "Entering podman unshare shell. Type 'exit' to return. Use 'podman unmount $container_id' later to cleanup."
        podman unshare
    )'''

[query]
    prompt                = "mount> "
    prompt_style.fg       = "Cyan"

[tui]
    percentage = 100
