#!/bin/sh

if ! command -v fs >/dev/null 2>&1; then
  echo "Error: 'fs' is not installed or not in your PATH." >&2
  echo "Please install it from https://github.com/Squirreljetpack/fist" >&2
  exit 1
fi

if [ -t 0 ] ; then
  ob-vaults -g "$@"
else
  cat
fi |
while read -r line; do
  fs -I=false -t .md --list --format '{=}\t{-1.}' $line .
done |
fs :custom  --opener ob-open \
  --tail-sep '	' \
  --transform '
        local path, tail = ...
        local display = (tail and tail ~= "") and ("/" .. path):match("^.-/" ..
        tail:gsub("%W", "%%%1") .. "/(.*)") or path
        return path, display:gsub("^/+", ""):gsub("%.md$", ""), tail'
