# Full text search

[matcher]
ansi = true
require_column = 1

[start]
[start.command]
command = '''rg --column --line-number --no-heading --color=always --smart-case "$FZF_QUERY"'''
output = "{=1}:{=2}"

[columns]
max = 3
names = ["file", "pos", ""]
split = '^(.*?):(\d+:\d+):(.*)$'
default = "file"

[exit]
abort_empty = false

# --- Preview ---
[preview]
show = true
scroll.percentage = 70
scroll.index = "pos"

[[preview.layout]]
command = '''
line={2}
if command -v bat >/dev/null 2>&1; then
    bat --wrap=never --color=always -pp --highlight-line ${line%%:*} {1}
else
    cat {1}
fi
'''
border = { type = "LightDoubleDashed", color = "DarkGray", title = "File Contents" }
side = "top"
percentage = 50
min = 5
padding = 0

# --- UI ---

[query]
prompt_style.fg = "Red"

[tui]
percentage = 100

[results]
inactive_current_style.fg = "DarkGray"
inactive_current_style.bg = "Black"
scroll_wrap = true

[binds]
"enter" = "@accept"
"ctrl-r" = "@reload"
"ctrl-." = "NextColumn"
"?" = "SwitchPreview"

"0,1^^@accept" = "Become($EDITOR {1})"

# --- Scripts ---
"Start" = "@enter_rg"
# Reload on query change, disable reparsing, update bind
"@enter_rg" = [
    "Filtering(false)",
    '''Bind(QueryChange = Reload)''',
    # Prompt indicator
    '''Transform(
    if [[ -n "$MM_QUERY" ]]; then
        echo "SetStyledPrompt({blue,italic:(${MM_QUERY#\%1 })} )"
    else
        echo "SetPrompt(rg> )"
    fi

    echo "SetQuery($MM_STORE)"
    echo "Store($MM_QUERY)"
)''',
    "Bind(@reload = @enter_mm)",
]
"@enter_mm" = [
    "Filtering(true)",
    "Unbind(QueryChange)",
    '''Transform(
    if [[ -n "$MM_QUERY" ]]; then
        echo "SetPrompt(($MM_QUERY) )"
    else
        echo "SetStyledPrompt({blue,italic:wm> })"
    fi

    echo "SetQuery($MM_STORE)"
    echo "Store($MM_QUERY)"
)
''',
    "Bind(@reload = @enter_rg)",
]
