# Full text search

[matcher]
ansi = true

[start]
[start.command]
command = '''rg --column --line-number --no-heading --color=always --smart-case "$env:FZF_QUERY"'''
output = "{=1}:{=2}"

[columns]
max = 3
names = ["file", "pos", ""]
split = '^(.*?):(\d+:\d+):(.*)$'
default = 3

# --- Preview ---
[preview]
show = true
scroll.percentage = 70
scroll.index = 2

[[preview.layout]]
command = '''
$line = {2}
$file = {1}
$highlightLine = ($line -split ':')[0]

if (Get-Command bat -ErrorAction SilentlyContinue) {
    bat --wrap=never --color=always -pp $highlightLine $file
} else {
    Get-Content -LiteralPath $file -Raw
}
'''
border = { type = "LightDoubleDashed", color = "DarkGray", title = "File Contents" }
side = "top"
percentage = 50
min = 5
padding = 0

# --- UI ---

[query]
prompt_style.fg = "Red"

[tui]
percentage = 100

[results]
inactive_current_style.fg = "DarkGray"
inactive_current_style.bg = "Black"
scroll_wrap = true

[binds]
"enter" = "@accept"
"ctrl-r" = "@reload"
"ctrl-." = "NextColumn"
"?" = "SwitchPreview"

"0,1^^@accept" = "Become(powershell -Command \"& $env:EDITOR {1}\")"

# --- Scripts ---
"Start" = "@enter_rg"
# Reload on query change, disable reparsing, update bind
"@enter_rg" = [
    "Filtering(false)",
    '''Bind(QueryChange = Reload)''',
    # Prompt indicator
    '''Transform(
    if ($env:MM_QUERY) {
        $trimmedQuery = $env:MM_QUERY -replace '^%1\s*', ''
        Write-Output "SetStyledPrompt({blue,italic:($trimmedQuery)} )"
    } else {
        Write-Output "SetPrompt(rg> )"
    }

    Write-Output "SetQuery($env:MM_STORE)"
    Write-Output "Store($env:MM_QUERY)"
)''',
    "Bind(@reload = @enter_mm)",
]
"@enter_mm" = [
    "Filtering(true)",
    "Unbind(QueryChange)",
    '''Transform(
    if ($env:MM_QUERY) {
        Write-Output "SetPrompt(($env:MM_QUERY) )"
    } else {
        Write-Output "SetStyledPrompt({blue,italic:wm> })"
    }

    Write-Output "SetQuery($env:MM_STORE)"
    Write-Output "Store($env:MM_QUERY)"
    Write-Output "SwitchColumn(1)"
)
''',
    "Bind(@reload = @enter_rg)",
]
