# Find and pick emojis

[start]

[start.command]
command = '''zstd -dc "$(dirname -- "$MM_OVERRIDE")"/emoji.zst'''
additional = [
  "",
  '''zstd -dc "$(dirname -- "$MM_OVERRIDE")"/emoji_compat.zst''',
]

[envs]
ACTIVE_DICT = "emoji"

[header]
content = ['char', 'name', 'group', 'subgroup']

[columns]
split = "\\t"
names = ["char", "name", "group", "subgroup"]
default = "name"

# --- Preview ---
[[preview.layout]]
command = '''
if ((MM_INDEX == 0)); then
  char={char}
  hex=$(printf "U+%X\n" "'$char")
else
  emoji_seq=$(echo {char} | awk -F'-' '
      function hex2dec(h) {
          v = 0; h = toupper(h)
          for(k=1; k<=length(h); k++) {
              v = v * 16 + index("0123456789ABCDEF", substr(h, k, 1)) - 1
          }
          return v
      }
      function to_utf8_octal(c) {
          if (c <= 127) return sprintf("\\0%03o", c)
          if (c <= 2047) return sprintf("\\0%03o\\0%03o", 192 + int(c/64), 128 + (c%64))
          if (c <= 65535) return sprintf("\\0%03o\\0%03o\\0%03o", 224 + int(c/4096), 128 + int((c/64)%64), 128 + (c%64))
          return sprintf("\\0%03o\\0%03o\\0%03o\\0%03o", 240 + int(c/262144), 128 + int((c/4096)%64), 128 + int((c/64)%64), 128 + (c%64))
      }
      {
          for(i=1; i<=NF; i++) {
              dec = hex2dec($i)
              printf "%s", to_utf8_octal(dec)
          }
      }
  ')
  char="$(printf "%b" "$emoji_seq")"
  hex=$(echo {char} | awk -F'-' '{for(i=1;i<=NF;i++) printf "U+%s ", toupper($i)}')
fi

printf "%${COLUMNS}s\n" | tr ' ' '-'
echo "  $char  "{name}
printf "%${COLUMNS}s\n" | tr ' ' '-'
echo "Codes:    $hex"
echo "Group:    "{group}
echo "Subgroup: "{subgroup}
'''

# --- UI ---
[results]
min_width = 5

[binds]
"@reload" = "ReloadNext"
"@reload_2" = "ReloadPrev"
# copy rust escape \u{1F511}
"@copy" = '''CopyAsync(
if ((MM_INDEX == 0)); then
  echo {char}
else
  emoji_seq=$(echo {char} | awk -F'-' '
      function hex2dec(h) {
          v = 0; h = toupper(h)
          for(k=1; k<=length(h); k++) {
              v = v * 16 + index("0123456789ABCDEF", substr(h, k, 1)) - 1
          }
          return v
      }

      function to_utf8_octal(c) {
          if (c <= 127) return sprintf("\\0%03o", c)
          if (c <= 2047) return sprintf("\\0%03o\\0%03o", 192 + int(c/64), 128 + (c%64))
          if (c <= 65535) return sprintf("\\0%03o\\0%03o\\0%03o", 224 + int(c/4096), 128 + int((c/64)%64), 128 + (c%64))
          return sprintf("\\0%03o\\0%03o\\0%03o\\0%03o", 240 + int(c/262144), 128 + int((c/4096)%64), 128 + int((c/64)%64), 128 + (c%64))
      }

      {
          for(i=1; i<=NF; i++) {
              dec = hex2dec($i)
              printf "%s", to_utf8_octal(dec)
          }
      }
  ')
  printf "%b" "$emoji_seq"
fi
)'''

"@copy_all" = '''CopyAsync(
if ((MM_INDEX == 0)); then
    char={char}
    printf "\\\\u{%X}" "'$char"
else
    echo {char} | awk -F'-' '{for(i=1;i<=NF;i++) printf "\\u{%s}", toupper($i)}'
fi
)'''

"enter" = ["Print({=char})", "Quit(0)"]

"tty^^enter" = [
  '''Copy(
if ((MM_INDEX == 0)); then
  echo {char}
else
  emoji_seq=$(echo {char} | awk -F'-' '{for(i=1;i<=NF;i++) printf "\\U%08X", strtonum("0x" $i)}')
  printf "%b" "$emoji_seq"
fi
)''',
  "Quit(0)",
]

# --- Scripts ---
"Start" = '''Transform(
    HEADERS=(
      'emojis> '
      'emojis:more> '
    )
    setopt KSH_ARRAYS 2>/dev/null
    echo "SetPrompt(${HEADERS[$MM_INDEX]})"
)
'''
"Reloaded" = '''Transform(
    HEADERS=(
      'emoji> '
      'emojis:more> '
    )
    setopt KSH_ARRAYS 2>/dev/null
    echo "SetPrompt(${HEADERS[$MM_INDEX]})"
)
'''
